### ISSUE TITLE
Make icons background white 

### ISSUE THREAD

**Issue by santoshyadavdev** [this-is-learning/this-is-learning-website#13]
The Icons on web looks strange as it is matching the background, we need to make it white

![image](https://user-images.githubusercontent.com/11923975/162574830-e037453d-3f37-44f7-a2bb-48ad5280a8d1.png)

Also revisit the mobile navbar and icons as well

**Comment by yslDevelop** [comment]
Do you guys mind if I take this issue?

**Comment by santoshyadavdev** [comment]
Go for it 😊

**Comment by S-triemer** [comment]
I looked into it but I'm not sure if I understood you right.
Should the Icons be white or the background of the page?
I made the Icons white like this:

![Bildschirmfoto von 2022-04-09 19-45-47](https://user-images.githubusercontent.com/62814975/162585776-f0245be7-6d23-4fcd-8820-765c5abd06cb.png)

And what do you mean by revisit the mobile navbar and icons?

Should the Icons be white too like this:
![Bildschirmfoto von 2022-04-09 19-55-32](https://user-images.githubusercontent.com/62814975/162585942-daea3a88-2169-435a-964d-dde8604d99c8.png)

Or do you want a complete overhaul of the mobile navigation?

**Comment by santoshyadavdev** [comment]
This looks much better already thank you for mobile navigation, yes the alignment looks odd due to 2 icons.

**Comment by yslDevelop** [comment]
![image](https://user-images.githubusercontent.com/93795660/162586487-3f93f68c-1d39-43f9-ac12-4d2769c9cd79.png)
Mine looks same as the screenshot above. I'm looking into it why it's happening.

**Comment by yslDevelop** [comment]
![image](https://user-images.githubusercontent.com/93795660/162586551-128a56cf-db0c-4cc7-9a33-233714472b93.png)
Is this what you wanted?

**Comment by santoshyadavdev** [comment]
Yes 😊

**Comment by yslDevelop** [comment]
okay :) looks good.
quick question.
I added border when the mouse is hovered to indicate the user that this icon is clickable
if you don't want it, I can just drop it. 
need your opinion :)
![image](https://user-images.githubusercontent.com/93795660/162586731-112f700e-fad9-4644-8367-7698cd387c4a.png)

**Comment by santoshyadavdev** [comment]
Perfect, lets keep it, thank you so much

**Comment by yslDevelop** [comment]
Thank you for the fast response :) I would love to tackle down other issues if you have any :) have a great weekend 😀

**Comment by santoshyadavdev** [comment]
Thank you so much 💙 will create some more issues, also if you think there are any improvements which can be done, feel free to suggest 😊

**Comment by S-triemer** [comment]
Since I don't have much experience with GitHub yet, I don't know what the right place for further suggestions is, but your hamburger-menu for the mobile navigation also needs to be fixed I think.
If you try to click it, you can only click exactly on the bars and not on the space in between the bars. 

I would try to replace that button with another animated hamburger button if you want me to look into it.

Also do you want the Angular Twitter and Angular Dev Link in your Navigation to be aligned like this with the text on the right
![Bildschirmfoto von 2022-04-09 22-08-56](https://user-images.githubusercontent.com/62814975/162590103-d11e6353-23d2-40ea-ae97-61e9fa793e52.png)
 Or like this with the text below the Icon?
![Bildschirmfoto von 2022-04-09 22-10-15](https://user-images.githubusercontent.com/62814975/162590160-85afe061-7bb4-45af-a712-c273e35b2453.png)

**Comment by LayZeeDK** [comment]
Closed by #14. Thank you, @yslDevelop and @S-triemer! 🙇‍♂️
